version: '3'
services:
  unifi_controller:
    build: .
    volumes:
      - .:/app
    ports:
      - "4567:4567"
    environment:
      - USERNAME='user'
      - PASSWORD='pass'
      - SITE_NAME='site_name'
      - BASE_URL='https://192.168.1.1:443'
      - API_TOKEN=SOME_TOKEN


